{{- if .Values.mirror.enabled }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-mirror-pv-{{ .Release.Namespace }}
  labels:
    app: image-mirror
spec:
  storageClassName: local-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /data/images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-mirror-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mirror.storage.size }}
  volumeName: image-mirror-pv-{{ .Release.Namespace }}

{{- end }}
