apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lernvirt.fullname" $ }}-keygen
  annotations:
    "helm.sh/hook-weight": "10"   
spec:
  template:
    spec:
      serviceAccountName: {{ include "lernvirt.fullname" $ }}-gateway
      restartPolicy: OnFailure
      containers:
        - name: keygen
          image: public.ecr.aws/docker/library/alpine:3.21
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "/scripts/keygen.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "lernvirt.fullname" $ }}-keygen-script
            defaultMode: 0755
