apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lernvirt.fullname" $ }}-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "lernvirt.fullname" $ }}-gateway
  template:
    metadata:
      labels:
        app: {{ include "lernvirt.fullname" $ }}-gateway
    spec:
      serviceAccountName: {{ include "lernvirt.fullname" $ }}-gateway
      containers:
        - name: wg
          image: alpine:3.19
          securityContext:
            privileged: true
          ports:
            - containerPort: 51820
              protocol: UDP            
          command: ["/bin/sh", "/controller/controller.sh"]
          volumeMounts:
            - name: controller
              mountPath: /controller
            - name: {{ include "lernvirt.fullname" $ }}-config
              mountPath: /config
      volumes:
        - name: controller
          configMap:
            name: {{ include "lernvirt.fullname" $ }}-controller
            defaultMode: 0755
        - name: {{ include "lernvirt.fullname" $ }}-config
          emptyDir: {}
