apiVersion: v1
kind: Service
metadata:
  name: {{ include "lernvirt.fullname" $ }}-gateway
spec:
  type: NodePort
  selector:
    app: {{ include "lernvirt.fullname" $ }}-gateway
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: 51820
