apiVersion: v1
kind: Service
metadata:
  name: wg-gateway
spec:
  type: NodePort
  selector:
    app: wg-gateway
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: 51820
