{{- range $i := until (.Values.vm.count | int) }}
{{- $vm := fromYaml (include "vm.values" (dict "index" $i "values" $.Values)) }}

{{- if eq $.Values.os.family "windows" }}

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
        {{- include "lernvirt.labels" $ | nindent 8 }}        
    spec:
      domain:
        machine:
          type: q35
        firmware:
          bootloader:
            bios: {}
        cpu:
          cores: {{ $vm.cpu }}
          model: host-passthrough
        resources:
          requests:
            memory: {{ $vm.memory }}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
              macAddress: {{ include "lernvirt.macAddress" (dict "root" $ "index" $i) | quote }}              
              model: e1000              
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}

{{- else }}

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
        {{- include "lernvirt.labels" $ | nindent 8 }}        
    spec:
      domain:
        cpu:
          cores: {{ $vm.cpu }}
        resources:
          requests:
            memory: {{ $vm.memory }}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
                readonly: true
          interfaces:
            - name: default
              masquerade: {}
              macAddress: {{ include "lernvirt.macAddress" (dict "root" $ "index" $i) | quote }}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
---
{{- end }}

{{- end }}
