{{- range $i := until (.Values.vm.count | int) }}

{{- if eq $.Values.os.family "windows" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
  labels:
    kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
    {{- include "lernvirt.labels" $ | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
  ports:
    - name: rdp
      port: 3389
      targetPort: 3389

{{- else }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
  labels:
    kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
    {{- include "lernvirt.labels" $ | nindent 4 }}    
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
  ports:
    - name: ssh
      port: 22
      targetPort: 22
---
{{- end }}
{{- end }}
