{{- range $i := until ($.Values.vm.count | int) }}
{{- $vm := include "vm.values" (dict "index" $i "values" $.Values) | fromYaml }}

{{- if eq $.Values.os.family "windows" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
  ports:
    # immer RDP
    - name: rdp
      port: 3389
      targetPort: 3389

    # zusätzliche Ports
    {{- range $vm.ports | default list }}
    - name: tcp-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
    {{- end }}

{{- else }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/domain: {{ include "lernvirt.fullname" $ }}-vm-{{ $i }}
  ports:
    # immer SSH
    - name: ssh
      port: 22
      targetPort: 22

    # zusätzliche Ports
    {{- range $vm.ports | default list }}
    - name: tcp-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
    {{- end }}
---
{{- end }}
{{- end }}
