apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lernvirt.fullname" . }}-readonly
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lernvirt.fullname" . }}-readonly
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - services
      - secrets
      - persistentvolumeclaims
    verbs: ["get","list","watch"]
  - apiGroups: ["kubevirt.io"]
    resources:
      - virtualmachineinstances
    verbs: ["get","list","watch"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources:
      - datavolumes
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lernvirt.fullname" . }}-readonly
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lernvirt.fullname" . }}-readonly
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lernvirt.fullname" . }}-readonly
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lernvirt.fullname" . }}-readonly-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "lernvirt.fullname" . }}-readonly
type: kubernetes.io/service-account-token
